### ISSUE TITLE
change SDS011

### ISSUE THREAD

**Issue by mariopesch** [sensebox/SenseBoxMCU-Lib#2]
Change the SDS Library that you can read only one value (p25, p10).
The checkup if there is an error should be done in the library and not in the sketch. If there ist no error the p25 or p10 value should be returned, otherwise an error.

**Comment by janwirwahn** [comment]
`getPm25()` and `getPm10()` are  already managing error handling internally. They return particle concentrations in µg/m³ as a float. Functions for that were implemented in https://github.com/sensebox/SenseBoxMCU-Lib/commit/1b4a517e89b6c6765a9ea392a00f0bb36ae08182
I'll set both of the values to 0 in case of an error or if the device is heating up within the next commit.
